### PR TITLE
Mark tl as spam with user confirmation

### PR DESCRIPTION
**Pull request by r2dev2**
Basically does:
```
@r2dev2 just a quick note on what I mean

make it so that when the user first opens this update, the block list is cleared (so probably do it in the changelog component, but keep in mind that can be opened on demand)

add a confirmation dialog when a user is detected for spam, only add to the block list if the user confirms
```
-- @KentoNishi 

- [x] migration to clear spam block list
- [x] logic for user-confirmed spam blocking
- [x] ui for user-confirmed spam blocking

### CODE REVIEW

**Comment by r2dev2** [comment]
@KentoNishi can u do the ui for the spam blocking? I'm assuming it's a `<Dialog />`, but unsure and it's 1 am lmao. Modify `src/components/SpammerPrompt.svelte` for the ui. `spammerInQuestion` is either `null` or an author object. `markAsSpammer` is the callback for marking the user as a spammer and `markAsInnocent` will whitelist them from the spam detection.

**Comment by KentoNishi** [comment]
it's bwoken

image

**Comment by KentoNishi** [comment]
@r2dev2 i fixed reactivity, but im so confused

why do we have both `channelFilters` and `spammersDetected`??? why are the blocklists separate? can u change it so the spam detection thing uses channelFilters instead, merging all blocking functionality into one?

**Comment by r2dev2** [comment]
> @r2dev2 i fixed reactivity, but im so confused
> 
> why do we have both `channelFilters` and `spammersDetected`??? why are the blocklists separate? can u change it so the spam detection thing uses channelFilters instead, merging all blocking functionality into one?

Ok, I merged the spam functionality to use the normal `channelFilters` and `mchadUsers` stores. It also now uses a separate `spammersWhitelisted` store (integrated nicely cause I was deriving such a store later on lmao).

**Comment by KentoNishi** [comment]
@r2dev2 im confused again. how do i differentiate between tldex and chat users in `spammersWhitelisted`? can u make it so `spammersWhitelisted` stores the source? why does `channelFilters` have `{ name: '', blacklist: false, whitelist: false }`, even tho `whitelist` is never used? can we just have one place where all user whitelists and blacklists are stored as an array of `{ userId: string; source: 'chat' | 'tldex'; type: 'blacklist' | 'whitelist' }` or something like that? i really hate that we have multiple places where user stuff is stored, we NEED to merge everything into one

**Comment by ChrRubin** [comment]
I suggest adding a "default behaviour" option if people don't want to respond to the dialog every time, something like a "remember my choice" checkbox.

Defaulting to "block" will just be our previous behaviour, and defaulting "ignore" should just disable spam protection. The "whitelist" button should be greyed out when selecting a default since it doesn't really make sense.

Also would need to add a toggle to the spam protection settings for "always block" if this is added. "Always ignore" will just disable spam protection so we don't need an extra setting for that.

**Comment by r2dev2** [comment]
> @r2dev2 im confused again. how do i differentiate between tldex and chat users in `spammersWhitelisted`? can u make it so `spammersWhitelisted` stores the source? why does `channelFilters` have `{ name: '', blacklist: false, whitelist: false }`, even tho `whitelist` is never used? can we just have one place where all user whitelists and blacklists are stored as an array of `{ userId: string; source: 'chat' | 'tldex'; type: 'blacklist' | 'whitelist' }` or something like that? i really hate that we have multiple places where user stuff is stored, we NEED to merge everything into one

Spammer whitelist is different from an overall whitelist, channelFilter whitelist is supposed to allow all messages from the channel. Although looking at the code, idk if we're even implementing that part. But yea, we should refactor all the user information into one store. That may take a while so I'll do it in a separate pr (perhaps to this branch).

Should we implement @ChrRubin 's suggestion of default behavior and then release for now? Or should we just make a small temporary edit to whitelist taishi from spam detection and then do the whole user whitelist refactor?

**Comment by KentoNishi** [comment]
I have to add a whitelist dropdown, but for now I think we should probably just release. Rubin's suggestion and the refractor can come later ig

**Comment by ChrRubin** [comment]
We should at least have a way to edit the whitelist before releasing, right now there's no way to remove whitelists.

And yeah the whitelist boolean in `channelFilters` is unused, I don't think it'll cause problems if we just remove it. JS only complains if something doesn't exist, not when there's extra values after all.

**Comment by KentoNishi** [comment]
image

**Review by KentoNishi — APPROVED** [review]

**Comment by KentoNishi** [comment]
@ChrRubin when u wake up pls just quickly review, i wanna get this update out today thx

**Review by ChrRubin — APPROVED** [review]

**Pull request merged**
