### PR TITLE
mchad_to_tldex migration

### PR DESCRIPTION
**Pull request by MonMonMnemonics**
fully working migration to tldex
- 1 new constant in constant.js to add holodexapi adderss
- 1 change in message.svelte from mchad TL -> tldex check mark
- not really small changes in mchad.js

the migration is scheduled to be by the end of golden week, so most probably on next monday

### CODE REVIEW

**Comment by ChrRubin** [comment]
Since the whole script is pretty much rewritten, we might wanna just do it in TypeScript instead.

Also, would this migration affect older archived translations?

**Comment by MonMonMnemonics** [comment]
everything under src/js where mchad.js is located is all in js anyway. You can do that later if you want but for now just keep it as it is,

mchad has been sending translation to holodex as well for a long time now, so past archives should be ok

**Comment by ChrRubin** [comment]
Are super old archives gonna be sent to TLdex too? For example https://youtu.be/tTyLbWrGKNs which was probably before Holodex was even a thing.

MChad archives have translations to this VOD but not on TLdex.

**Comment by MonMonMnemonics** [comment]
June 2020, I feel old now.... it has been that long huh.

There is an "import from mchad" button in https://staging.holodex.net/scriptmanager. Unfortunately translators have to do it manually since there's no way to connect mchad and holodex account directly. But hey, it's just 3 clicks process and I'll at least urge them to do so.

**Comment by KentoNishi** [comment]
Can we have both mchad and tldex connected up in that case? It'd be bad if previously accessible tls became inaccessible becuz of this vendor switch. Just to make sure, this effectively means mchad is no more, and tldex is taking over, right?

**Comment by MonMonMnemonics** [comment]
You can use old code to get tl from mchad and the new code to get tl from tldex, then work out the duplication. 

But just to let you know, mchad is effectively closing soon. Ph.D in particle physics is hardcore, last month alone I was only able to work on the migration in two occasions and one of them was thanks to golden week.

**Comment by KentoNishi** [comment]
damn good luck with your defense, whenever it is

**Comment by ChrRubin** [comment]
> But just to let you know, mchad is effectively closing soon. Ph.D in particle physics is hardcore, last month alone I was only able to work on the migration in two occasions and one of them was thanks to golden week.

Will it still be up for translators to use or are they expected to move to TLdex as well? Also will the old archives that are not on TLdex still be accessible?

> You can use old code to get tl from mchad and the new code to get tl from tldex, then work out the duplication.

Assuming the old archives will still be available, we can just add TLdex as a seperate source and deduplication *should* work as is. Although I wonder if there'll be weirdness with having TLs with the exact same timestamps from 2 sources, such as one TL being marked as from MChad and the next one being marked as from TLdex.

**Comment by MonMonMnemonics** [comment]
I'm planning to keep it up for 1-2 month during the transfer to give translator time to import their scripts as well as to clear up bugs. After that, it will be completely shut down except for the bot since some people asked me to keep that up.

**Comment by ChrRubin** [comment]
I've made a new branch on  [`tldex`](https://github.com/LiveTL/LiveTL/tree/tldex) ([diff](https://github.com/LiveTL/LiveTL/compare/tldex)) and copied the modified script to a separate file so TLdex can be its own source alongside MChad. This will let us still show old translations that are on MChad but not on TLdex, as long as the MChad archives stay up.

If that's the path we wanna take, I can merge it into this branch or open a new PR. If not, the changes here seems fine to me.

**Comment by MonMonMnemonics** [comment]
I'll leave the decision to the development team.

Just a note that currently holodex only have websocket and through my discussion with them, liveTL is proxying through mchad to reduce the load and I'm planning to downsize the server to bare minimum.

**Comment by KentoNishi** [comment]
heads up, mon figured out automated migration with the holodex devs, so it's safe to transition all mchad functionality to dex now! @ChrRubin do u have time to whip up a ts version of this? im getting crushed with covid, finals, and graduation stuff...

**Comment by KentoNishi** [comment]
https://github.com/LiveTL/LiveTL/pull/413

**Pull request merged**
