### PR TITLE
Spotlight translator

### LINKED ISSUE #272: Isolate translators
Button to isolate a single translator temporarily

### PR DESCRIPTION
**Pull request by r2dev2**
Fixes #272

### CODE REVIEW

**Comment by KentoNishi** [comment]
holy sht ur speed, i'll review later

**Comment by r2dev2** [comment]
> holy sht ur speed, i'll review later

No, I'm pomu.

**Review by KentoNishi — CHANGES_REQUESTED** [review]
image

while being spotlighted, the caption box flashes even when no new messages from that specific user are being shown.

there also needs to be a button to un-spotlight.

**Comment by KentoNishi** [comment]
image

also switched to mdiPin cuz it makes more sense than that weird circle square icon

**Review by ChrRubin — CHANGES_REQUESTED** [review]
In addition to what Kento suggested, this also has a small bug with deduplication, where for example if Taishi's mchad is spotlighted, messages from his YTC will never be shown even if it is the earlier message (I've seen it happen on VODs).

Or even worse, if for whatever reason people somehow spotlight his YTC, it'll almost never have messages lmao

**Comment by r2dev2** [comment]
I'm going to refactor this entire thing later into having a store which has all the translations and a store which has all the displayed translations. The future refactor will allow us to have better unbanning and unspotlighting.

**Review by ChrRubin — CHANGES_REQUESTED** [review]
There's some strange behaviour when spotlighting an mchad user:
- Messages from other users that are already shown aren't hidden. Future messages from other users do not get shown, which is expected behaviour.
- The latest mchad message will be duplicated.
- The unspotlight button does not appear.

image

**Comment by ChrRubin** [comment]
> I'm going to refactor this entire thing later into having a store which has all the translations and a store which has all the displayed translations. The future refactor will allow us to have better unbanning and unspotlighting.

Can probably do that when we get to the smelte migration. I've already done a few breaking changes to the background messaging pipeline in smelte HC, and I'm considering moving the entire YTC queue logic to the background script so HC and LTL only have to deal with showing/filtering the messages.

**Comment by r2dev2** [comment]
> > I'm going to refactor this entire thing later into having a store which has all the translations and a store which has all the displayed translations. The future refactor will allow us to have better unbanning and unspotlighting.
> 
> Can probably do that when we get to the smelte migration. I've already done a few breaking changes to the background messaging pipeline in smelte HC, and I'm considering moving the entire YTC queue logic to the background script so HC and LTL only have to deal with showing/filtering the messages.

I meant like on a higher level. Like have the ``items`` reactive array be a store that is globally available so we can globally see which translations are displayed and which are hidden. The ``sources`` object would likely not be changed and instead this would use an ``aggregates`` object.

**Comment by KentoNishi** [comment]
image

**Review by KentoNishi — APPROVED** [review]

**Comment by KentoNishi** [comment]
i approb

**Review by KentoNishi — APPROVED** [review]

**Review by ChrRubin — APPROVED** [review]

**Pull request merged**
