### PR TITLE
Use icons for settings tabs

### PR DESCRIPTION
**Pull request by r2dev2**
This uses icons for the settings tabs and tooltips are displayed under each tab for more context. Other ideas for better settings are welcome.

### CODE REVIEW

**Comment by KentoNishi** [comment]
image
i can't handle the off-center style lmao i gotta fix

**Comment by r2dev2** [comment]
> image
> i can't handle the off-center style lmao i gotta fix

Hold up, I remember that I fixed that, I think i forgot to commit it lmao

**Comment by r2dev2** [comment]
Darn it, seems like it's doing the weird flickery thing again

**Comment by r2dev2** [comment]
> > image
> > i can't handle the off-center style lmao i gotta fix
> 
> Hold up, I remember that I fixed that, I think i forgot to commit it lmao

Never mind, it seems like my fix only works for popout mode. In embed mode, it is 1 rem off from center if that helps. Can either @KentoNishi or @ChrRubin fix this?

**Comment by KentoNishi** [comment]
i'll take a look

**Comment by KentoNishi** [comment]
i think i know why this is an issue

to enable smooth draggables and sht on firefox, the body actually overflows 20px on each side of the screen in livetl view. materialify calculates positions relative to the body, but then displays it absolute so it's off by 20px

**Comment by KentoNishi** [comment]
image
booooooom baby

**Review by KentoNishi — APPROVED** [review]

**Pull request merged**
