### PR TITLE
Ability To Invert Youtube Chat And LiveTL

### LINKED ISSUE #365: [Feature]: Option to switch positions of YTC and filtered TLs
### Checklist

- [X] This is a suggestion for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to suggest a feature for Hyperchat.
- [X] This is a suggestion for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to suggest features for those platforms.
- [X] I have checked for a duplicate or similar feature request/issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

Some people might prefer having filtered TLs on top and YTC at the bottom.

### Describe the solution you'd like

Add an option to switch the position of YTC and filtered TLs. Should work for both horizontal and vertical chat split.

### Describe alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Eroxl**
# About
Added the ability to invert YouTube chat and Live TL. Works in vertical / horizontal mode and if the video is on top or bottom.

# Examples
## Inverted
Screen Shot 2021-12-13 at 1 32 28 PM

## Not Inverted
Screen Shot 2021-12-13 at 1 32 35 PM

Closes #365

### CODE REVIEW

**Comment by r2dev2** [comment]
It's fine for now but next time can you make a separate branch on your fork and then send a pull request from that branch to LiveTL/develop? When you send pull requests from your develop branch, there are sometimes weird git errors (although I've resolved them for now with `git branch -D Eroxl/develop` and then pulled).

rejected pull

**Comment by KentoNishi** [comment]
imagine using gh cli for pr checkout lmao

i actually just add the fork as a remote and pull the branch

**Comment by Candygoblen123** [comment]
I usually just clone the whole repo into a temp dir, and delete it when I’m done.  And do the merge in GitHub web

**Comment by r2dev2** [comment]
My computer's being really weird with selenium because chromium just updated and everything is in chaos now. Can someone figure out how to make the e2e tests run for this branch?

**Comment by Candygoblen123** [comment]
Screen Shot 2021-12-13 at 4 41 23 PM

**Comment by r2dev2** [comment]
> Screen Shot 2021-12-13 at 4 41 23 PM

I can run the jest tests, not the e2e ones. Can you do `yarn e2e` to run the e2e ones? I think you need to do `python3 -m pip install selenium==3.141.0 autoparaselenium>=0.1.9 requests` to install dependencies then it'll work.

**Review by r2dev2 — APPROVED** [review]

**Comment by r2dev2** [comment]
I got the selenium e2e tests to run on my computer and they were successful.

**Comment by KentoNishi** [comment]
im gonna change this to a radio select instead of a checkbox, along with a variable label depending on the layout. plz dont merge this yet thx

**Comment by KentoNishi** [comment]
i'll do this this weekend sorry lol

**Comment by KentoNishi** [comment]
sht wait i messed up

**Comment by KentoNishi** [comment]
dw i have a local copy

**Pull request closed without merging**
