### PR TITLE
LiveTL API Read-only integration

### PR DESCRIPTION
**Pull request by r2dev2**
This enables users to read translations from the LiveTL API for both livestreams and vods. The integration has not been tested yet and the ability to write to the api from within YouTube's chat will come in the translator mode update.

### CODE REVIEW

**Comment by KentoNishi** [comment]
awaiting ur checkbox

**Comment by GrumpyBear57** [comment]
> Oh, I had it just load the registered list on startup of the program and lookup from the registered list on startup. This also handles the case that a translator may change their display name or other information like verification status.

Suppose this should be fine, I just wanted to make sure that the api wasn't going to get hit on the full endpoint by (potentially) hundreds of clients anytime a new translator submitted something, a lot easier to just serve the single TLr compared to all of them.

**Review by GrumpyBear57 — COMMENTED** [review]
Looks good other than I'm still not sure how it'll handle a new translator who registered and starts sending TLs after the initial list retrieval.

**Comment by r2dev2** [comment]
Aight, I can't seem to figure out how to launch the translator client, gonna assume it works now and test later.

**Pull request merged**
