### PR TITLE
Fixed: Messages with only emojis never gets filtered

### LINKED ISSUE #331: Messages with only emojis never gets filtered
Messages that only contain emojis do not contain any text and will never be shown by the LiveTL output, since the text property is required in the messages stores.

This can be undesirable when LiveTL is set to show all mod/owner messages (or even custom user filters), but messages from these users do not get filtered when it only contains emojis.

### PR DESCRIPTION
**Pull request by Eroxl**
Fixes #331

### CODE REVIEW

**Review by r2dev2 — APPROVED** [review]

**Comment by r2dev2** [comment]
Wait why isn't it queuing the e2e tests?

**Comment by GrumpyBear57** [comment]
> 
> 
> Wait why isn't it queuing the e2e tests?

Probably because of first time contributor settings

**Comment by r2dev2** [comment]
> > Wait why isn't it queuing the e2e tests?
> 
> Probably because of first time contributor settings

I said approve workflow and only 2 checks ran.

**Comment by r2dev2** [comment]
Oh it's because the e2e tests are for push only.

**Comment by r2dev2** [comment]
I ran the e2e tests locally, it seems fine.

**Pull request merged**
