### PR TITLE
tldex

### PR DESCRIPTION
**Pull request by KentoNishi**

### CODE REVIEW

**Comment by KentoNishi** [comment]
mchad is now down and disconnected, so there isn't much of a reason to keep the code anymore, but oh well

**Review by r2dev2 — APPROVED** [review]
Gonna just set the `enableTldexTl` to be equal to the `enableMCHADTl` store so that we keep the user preference of those who disabled mchad.

**Review by ChrRubin — APPROVED** [review]
One side effect to note is that YTC translations might also get the TLdex badge depending on which message is received first, since TLdex catches YTC TLs too.

**Comment by r2dev2** [comment]
> One side effect to note is that YTC translations might also get the TLdex badge depending on which message is received first, since TLdex catches YTC TLs too.

Should we play with the verified parameter in the tldex url then? What does that verified number do?
verified

**Comment by ChrRubin** [comment]
> Should we play with the verified parameter in the tldex url then? What does that verified number do? verified

I would guess that's for the YT verified badge, but chat messages is not on their public API reference.

**Comment by KentoNishi** [comment]
good enough for now, release will be tomorrow

**Pull request merged**
